import { useState } from "react";
import type { NextPage } from "next";
import Head from "next/head";
import getBlockchain from "../scripts/MockBlockchain";
import { Block, Blockchain } from "../scripts/blockchain";
import BlockTransactions from "../components/BlockTransactions";

const Home: NextPage = () => {
    const [blockchain, setBlockchain] = useState<Blockchain>(getBlockchain());

    console.log("Blockchain : ", blockchain);

    return (
        <div className="">
            <Head>
                <title>Blockchain POC</title>
                <meta
                    name="Blockchain proof-of-cencept (POC)"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className="flex flex-col items-center p-10 w-full text-white bg-neutral-900">
                <h1 className="text-4xl font-bold text-blue-500">
                    Blockchain POC
                </h1>
                {blockchain.blocks.map(
                    (
                        {
                            version,
                            previousBlockHash,
                            merkleRoot,
                            timestamp,
                            difficulty,
                            nonce,
                            hash,
                            transactions,
                        }: Block,
                        index: number
                    ) => (
                        <div className="p-10 my-6 bg-grdient-to-b from-zinc-900 to zinc-800 rounded-xl  shadow-xl shadow-gray-800">
                            <h1 className="text-3xl text-amber-300">
                                {index === 0
                                    ? "Genesis Block"
                                    : `Block height : ${index}`}
                            </h1>

                            <div className="p-4 border-b-2 mb-4 text-lg">
                                <h1 className="text-2xl">Block Header</h1>
                                <p>Version: {version}</p>
                                <p className="text-blue-500">
                                    Previous block hash:{" "}
                                    {previousBlockHash || "None"}
                                </p>
                                <p>Merkle Root: {merkleRoot}</p>
                                <p>Timestamp: {timestamp}</p>
                                <p>Difficulty: {difficulty}</p>
                                <p>Nonce: {nonce}</p>
                            </div>

                            <h1 className="text-xl mx-4 text-blue-500">
                                Block hash : {hash}
                            </h1>

                            <BlockTransactions transactions={transactions} />
                        </div>
                    )
                )}
            </main>
        </div>
    );
};

export default Home;
